### ISSUE TITLE
[webpack team proposal] ESM in browsers vs bundlers

### ISSUE THREAD

**Issue by sokra** [JSKongress/JS-Kongress-Munich-In-Deep-Track#10]
**Session Title:**
ESM in browsers vs bundlers

**Session Abstract:**
* How are we using ESM in future? Bundled or native?
  * Can we find a way to coexist?

**Approximate Duration:** 
30 minutes

**Your Name:**
Tobias Koppers

**Your Twitter handle:**
wSokra

**Requirements:**
[x] No
[ ] Yes => Please share what do you need.

**Complexity:**
[ ] Advanced
[x] Intermediate
[ ] Beginner

**Other information:**

**Comment by jhnns** [comment]
Maybe we should call the session "Are bundlers necessary in the future"? because I would like to talk about the bigger picture, not just ESM vs. bundlers. What about minification? What about chunking in general (putting multiple modules into the same file)? Is H2 push solving it?
But maybe you thought about the same @sokra?

**Comment by jhnns** [comment]
In this case, we should increase the duration to 60 minutes. Or is it better to separate this discussion?
